name: auth-service

services:
  auth-api:
    container_name: auth-api
    build:
      context: ./AuthService
      dockerfile: dockerfile
    volumes:
      - ./AuthService:/srv/www/AuthService
    ports:
      - "${AUTH_PORT:-3001}:3000"
    environment:
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_USER=auth_user
      - DB_PASS=auth_password
      - DB_NAME=auth_db
      - REDIS_HOST=auth-redis
      - REDIS_PORT=6379
    depends_on:
      - auth-db
      - auth-redis
    networks:
      - bokuno-network

  auth-db:
    container_name: auth-db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "54321:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - bokuno-network

  # --- Caché (Redis) ---
  auth-redis:
    container_name: auth-redis
    image: redis:alpine
    restart: always
    volumes:
      # Persistencia de datos (opcional para Redis, pero recomendado)
      - auth_redis_data:/data
    # Comando para habilitar la persistencia en disco en Redis
    command: redis-server --appendonly yes
    networks:
      - bokuno-network

# --- Definición de Volúmenes ---
volumes:
  auth_postgres_data:
    name: auth_pg_data # Nombre explícito para encontrarlo fácil
  auth_redis_data:
    name: auth_redis_data

# --- Definición de Redes ---
networks:
  bokuno-network:
    external: true